# Generated by Django 3.2.23 on 2024-04-24 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demoapp', '0001_initial'),
        ('books', '0005_alter_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('return_status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned')], max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.user')),
            ],
        ),
    ]
